### PR TITLE
Ability to Create Embeds using an API

### PR DESCRIPTION
**Pull request by itschasa**
Added support for creating embeds using URLs and an API I made and host.

API docs are here: https://docs.e.chasa.wtf/
Site is here: https://e.chasa.wtf/

### CODE REVIEW

**Comment by itschasa** [comment]
wait i'm retarded and didn't included the utilities.go file, i'll commit it in the morning. i'm in bed rn lmao.

**Comment by itschasa** [comment]
there we go, added all the code now.

**Comment by V4NSH4J** [comment]
Hey Chasa! Can you explain this idea a bit more to me, we're using a website to make the embed and then we append it to the end of the message?

**Comment by itschasa** [comment]
Only making the embed, this creates a link for the user to then put into the message.json file, as they might want to put it somewhere specific.

**Comment by V4NSH4J** [comment]
Sounds awesome, I'll merge this and make some changes before releasing today/tomorrow's update!

**Comment by V4NSH4J** [comment]
Also let's say, someone visits your embed website using the link they add in message.json, what would they see?

**Comment by itschasa** [comment]
In the embed file, there is a field called "redirect". This is where the user enters the url where they want the user to be redirected.

I plan to host this for quite a few years, since it's just running on one of my repls (premium). I've got a discount as well on replit so I'll keep it going for ages. I use it for my auth server as well so I need that to be up.

**Comment by itschasa** [comment]
just realised i didn't upload the embed.json file. i'll upload it as soon as possible.

**Comment by V4NSH4J** [comment]
Awesome, let me know when I can merge it.

**Comment by cateee69** [comment]
can't you get people's ip with this 💀

**Comment by V4NSH4J** [comment]
@itschasa You'd have to make some changes, I restructured some files.

**Comment by itschasa** [comment]
yea i just wanted to get a draft of what i think it should look like. i'm not experienced with go's syntax so i just went with what worked.

what changes you think will be needed on the backend of the api?

**Comment by V4NSH4J** [comment]
It's looking alright for the backend part, just that if someone visits your embed website using the link in the message, you can redirect them if not already doing that. 

in DMDGO v1.9.0 I restructured some files so I can't merge this as there are conflicts, you'd have to follow the new structure.

**Comment by itschasa** [comment]
i'll work on implementing the embeds based on the current file structure. 

redirects are already a thing. on the docs you can see the embed structure on the success response.

**Comment by itschasa** [comment]
some reason go is deciding to be annoying. i'll try again soon. i cant import scripts from github repos for some reason.

**Pull request closed without merging**
