### PR TITLE
Added YAML Support for Config File

### PR DESCRIPTION
**Pull request by itschasa**
Added support for a YAML file to be used instead of a JSON file.

Useful as you can add comments to YAML files, but not in JSON files.
That way, users can read about the setting in the file, instead of asking about it or going onto `readme.md`. 

Note: JSON File will take priority, however that can be changed easily.

### CODE REVIEW

**Comment by V4NSH4J** [comment]
Hey @itschasa Thank you for the PR!
I don't think we need backwards compatibility with the json config, so it can be removed. Also if the config is being re-worked, it would be a nice addition to group the similar options. Like all proxy options under a key proxy: or all DM related ones under a key DMs. Let me know what you think!

**Comment by itschasa** [comment]
I can remove the json compatibility, and the yml file has groups, but not groups like:
`dm:
   individual_delay: 6
   etc...`

it has it via comments;
`# ----  Proxy Options  ---- #

# description, etc....
# default: 6
# type: int
individual_delay: 6`

**Comment by V4NSH4J** [comment]
Yeah, you should remove the JSON compatibility... I'll make a dev branch for this where we can further make changes.

**Comment by itschasa** [comment]
I've now removed the JSON compatibility, only config.yml will work now.

**Comment by itschasa** [comment]
Sorry for delay, I'm lazy af lmao.

**Comment by V4NSH4J** [comment]
Looks good, needs a bit more work but I'll take it from here! Thanks and welcome to DMDGO's Contributors.

**Comment by itschasa** [comment]
epic

**Pull request merged**
